library(tidyverse);
setwd("~/Desktop/github/OOTP-Data-Management");
##requires running qry_ootpCSV.R & qry_league_setup.R


players=function(){
  
  ootpCSV("players.csv") %>% 
    filter(retired==0 & hidden==0) %>% 
    left_join(as.data.frame(cbind(position=1:13, 
                                  posDESC=c("P", "C", "1B", "2B", "3B", 
                                            "SS", "LF", "CF", "RF", 
                                            "DH", "SP", "RP", "CP"))) %>% 
                mutate(position=as.numeric(position)), 
              by="position") %>%
    left_join(leagues() %>% 
                select(leagueID, leagueDESC, levelID, season_year, file_date), 
              by=c("league_id"="leagueID")) %>%
    left_join(cities() %>% 
                transmute(city_of_birth_id=cityID, 
                          birthcityDESC=ifelse(nationID==206, 
                                               paste0(cityNAME, ", ", stateDESC), 
                                               paste0(cityNAME, ", ", nationDESC))), 
              by="city_of_birth_id") %>%
    left_join(teams() %>%
                transmute(teamID, 
                          teamDESC, 
                          orgID,
                          orgDESC), 
              by=c("team_id"="teamID")) %>%
    left_join(nations() %>% 
                transmute(nation_id=nationID, 
                          nationDESC), 
              by="nation_id") %>%
    transmute(playerID=player_id, 
              playerNAME=paste(first_name, last_name), 
              posID=position, 
              posDESC, 
              leagueID=league_id,
              leagueDESC=ifelse(free_agent==1, 
                                "FA", 
                                leagueDESC),
              levelID=ifelse(free_agent==1, 
                             0, 
                             levelID), 
              orgID=organization_id,
              orgDESC=ifelse(leagueID==0, 
                             "FA",
                             orgDESC),
              teamID=team_id, 
              teamDESC=ifelse(leagueID==0, 
                              "FA",
                              teamDESC),
              bats=ifelse(bats==1, 
                          "R", 
                          ifelse(bats==2, 
                                 "L", 
                                 ifelse(bats==3, 
                                        "S", 
                                        NA))), 
              throws=ifelse(throws==1, 
                            "R", 
                            ifelse(throws==2, 
                                   "L", 
                                   NA)), 
              date_of_birth=lubridate::ymd(date_of_birth),
              baseballAGE=floor(as.numeric(difftime(
                lubridate::ymd(paste0(season_year, "06-30")),
                date_of_birth))/365.25),
              birthcityID=city_of_birth_id, 
              birthcityDESC,
              nationID=nation_id, 
              nationDESC,
              season_year=ifelse(is.na(season_year), 
                                 unique(leagues() %>% 
                                          filter(levelID==1) %>% 
                                          pull(season_year)), 
                                 season_year),
              file_date,
              file_name)
  
};






injuries=function(){
  
  ootpCSV("players.csv") %>% 
    filter(retired==0 & hidden==0) %>%
    filter(injury_is_injured > 0) %>%
    transmute(
      player_id,
      injury_is_injured,
      injury_dl_left, 
      injury_dl_playoff_round, 
      injury_id, 
      injury_left, 
      injury_id2, 
      injury_dtd_injury2, 
      injury_left2, 
      injury_dtd_injury, 
      injury_dtd_effect=dtd_injury_effect, 
      injury_dtd_effect_hit=dtd_injury_effect_hit, 
      injury_dtd_effect_throw=dtd_injury_effect_throw, 
      injury_dtd_effect_run=dtd_injury_effect_run, 
      injury_dtd_injury2, 
      injury_dtd_effect2=dtd_injury_effect2, 
      injury_dtd_effect_hit2=dtd_injury_effect_hit2, 
      injury_dtd_effect_throw2=dtd_injury_effect_throw2, 
      injury_dtd_effect_run2=dtd_injury_effect_run2, 
      injury_career_ending, 
      file_name, 
      file_date)
  
};
ratings=function(){
  
  rtg_convert=function(x){
    
    ifelse(x>=192, 
           80, 
           ifelse(x>=175, 
                  75, 
                  ifelse(x>=159, 
                         70, 
                         ifelse(x>=142, 
                                65, 
                                ifelse(x>=125, 
                                       60, 
                                       ifelse(x>=109, 
                                              55, 
                                              ifelse(x>=92, 
                                                     50, 
                                                     ifelse(x>=75, 
                                                            45, 
                                                            ifelse(x>=59, 
                                                                   40, 
                                                                   ifelse(x>=42, 
                                                                          35, 
                                                                          ifelse(x>=25, 
                                                                                 30, 
                                                                                 ifelse(x>=9, 
                                                                                        25, 
                                                                                        ifelse(x>=1, 
                                                                                               20, 
                                                                                               0)
                                                                                 )
                                                                          )
                                                                   )
                                                            )
                                                     )
                                              )
                                       )
                                )
                         )
                  )
           )
    )
    
  };
  
  ootpCSV("players_scouted_ratings.csv") %>% 
    left_join(ootpCSV("players.csv") %>%
                transmute(player_id,
                          actualAGE=round(as.numeric(difftime(
                            file_date, date_of_birth))/365.25, 2),
                          season_year=leagues() %>% filter(leagueID==100) %>% pull(season_year),
                          height=round(height*0.393701), 
                          weight,
                          injury_prone_ovr=rtg_convert(prone_overall), 
                          injury_prone_leg=rtg_convert(prone_leg), 
                          injury_prone_back=rtg_convert(prone_back), 
                          injury_prone_arm=rtg_convert(prone_arm), 
                          person_type, 
                          personality_greed=rtg_convert(personality_greed), 
                          personality_loyalty=rtg_convert(personality_loyalty), 
                          personality_play_for_winner=rtg_convert(personality_play_for_winner), 
                          personality_work_ethic=rtg_convert(personality_work_ethic), 
                          personality_intelligence=rtg_convert(personality_intelligence), 
                          personality_leader=rtg_convert(personality_leader)), 
              by="player_id") %>%
    transmute(
      playerID=player_id,
      actualAGE,
      scouting_coach_id, 
      scouting_accuracy, 
      overall=rtg_convert(overall_rating), 
      potential=rtg_convert(talent_rating),
      height, 
      weight,
      contact_overall=rtg_convert(batting_ratings_overall_contact), 
      contact_potential=rtg_convert(batting_ratings_talent_contact), 
      contact_left=rtg_convert(batting_ratings_vsl_contact), 
      contact_right=rtg_convert(batting_ratings_vsr_contact), 
      power_overall=rtg_convert(batting_ratings_overall_power), 
      power_potential=rtg_convert(batting_ratings_talent_power), 
      power_left=rtg_convert(batting_ratings_vsl_power), 
      power_right=rtg_convert(batting_ratings_vsr_power), 
      gap_overall=rtg_convert(batting_ratings_overall_gap), 
      gap_potential=rtg_convert(batting_ratings_talent_gap), 
      gap_left=rtg_convert(batting_ratings_vsl_gap), 
      gap_right=rtg_convert(batting_ratings_vsr_gap), 
      eye_overall=rtg_convert(batting_ratings_overall_eye), 
      eye_potential=rtg_convert(batting_ratings_talent_eye), 
      eye_left=rtg_convert(batting_ratings_vsl_eye), 
      eye_right=rtg_convert(batting_ratings_vsr_eye), 
      avoidK_overall=rtg_convert(batting_ratings_overall_strikeouts), 
      avoidK_potential=rtg_convert(batting_ratings_talent_strikeouts), 
      avoidK_left=rtg_convert(batting_ratings_vsl_strikeouts), 
      avoidK_right=rtg_convert(batting_ratings_vsr_strikeouts), 
      bunt_sac=rtg_convert(batting_ratings_misc_bunt), 
      bunt_hit=rtg_convert(batting_ratings_misc_bunt_for_hit), 
      gb_hitter=batting_ratings_misc_gb_hitter_type, 
      fb_hitter=batting_ratings_misc_fb_hitter_type, 
      speed=rtg_convert(running_ratings_speed), 
      steal_ability=rtg_convert(running_ratings_stealing), 
      baserunning=rtg_convert(running_ratings_baserunning),
      if_range=rtg_convert(fielding_ratings_infield_range), 
      if_arm=rtg_convert(fielding_ratings_infield_arm), 
      if_error=rtg_convert(fielding_ratings_infield_error), 
      if_tdp=rtg_convert(fielding_ratings_turn_doubleplay), 
      of_range=rtg_convert(fielding_ratings_outfield_range), 
      of_arm=rtg_convert(fielding_ratings_outfield_arm), 
      of_error=rtg_convert(fielding_ratings_outfield_error), 
      c_ability=rtg_convert(fielding_ratings_catcher_ability), 
      c_arm=rtg_convert(fielding_ratings_catcher_arm), 
      stamina=rtg_convert(pitching_ratings_misc_stamina), 
      velocity=pitching_ratings_misc_velocity, 
      armslot=pitching_ratings_misc_arm_slot, 
      ground_fly=pitching_ratings_misc_ground_fly, 
      hold_runners=rtg_convert(pitching_ratings_misc_hold),
      stuff_overall=rtg_convert(pitching_ratings_overall_stuff), 
      stuff_potential=rtg_convert(pitching_ratings_talent_stuff), 
      stuff_left=rtg_convert(pitching_ratings_vsl_stuff), 
      stuff_right=rtg_convert(pitching_ratings_vsr_stuff), 
      control_overall=rtg_convert(pitching_ratings_overall_control), 
      control_potential=rtg_convert(pitching_ratings_talent_control), 
      control_left=rtg_convert(pitching_ratings_vsl_control), 
      control_right=rtg_convert(pitching_ratings_vsr_control), 
      movement_overall=rtg_convert(pitching_ratings_overall_movement), 
      movement_potential=rtg_convert(pitching_ratings_talent_movement), 
      movement_left=rtg_convert(pitching_ratings_vsl_movement), 
      movement_right=rtg_convert(pitching_ratings_vsr_movement), 
      fastball=ifelse(pitching_ratings_pitches_fastball>0, 1, 0), 
      fastball_rating=rtg_convert(pitching_ratings_pitches_fastball), 
      fastball_potential=rtg_convert(pitching_ratings_pitches_talent_fastball),
      splitter=ifelse(pitching_ratings_pitches_splitter>0, 1, 0), 
      splitter_rating=rtg_convert(pitching_ratings_pitches_splitter), 
      splitter_potential=rtg_convert(pitching_ratings_pitches_talent_splitter), 
      sinker=ifelse(pitching_ratings_pitches_sinker>0, 1, 0), 
      sinker_rating=rtg_convert(pitching_ratings_pitches_sinker), 
      sinker_potential=rtg_convert(pitching_ratings_pitches_talent_sinker), 
      cutter=ifelse(pitching_ratings_pitches_cutter>0, 1, 0), 
      cutter_rating=rtg_convert(pitching_ratings_pitches_cutter), 
      cutter_potential=rtg_convert(pitching_ratings_pitches_talent_cutter),
      changeup=ifelse(pitching_ratings_pitches_changeup>0, 1, 0), 
      changeup_rating=rtg_convert(pitching_ratings_pitches_changeup), 
      changeup_potential=rtg_convert(pitching_ratings_pitches_talent_changeup), 
      circlechange=ifelse(pitching_ratings_pitches_circlechange>0, 1, 0), 
      circlechange_rating=rtg_convert(pitching_ratings_pitches_circlechange), 
      circlechange_potential=rtg_convert(pitching_ratings_pitches_talent_circlechange),
      knuckleball=ifelse(pitching_ratings_pitches_knuckleball>0, 1, 0), 
      knuckleball_rating=rtg_convert(pitching_ratings_pitches_knuckleball), 
      knuckleball_potential=rtg_convert(pitching_ratings_pitches_talent_knuckleball), 
      slider=ifelse(pitching_ratings_pitches_slider>0, 1, 0), 
      slider_rating=rtg_convert(pitching_ratings_pitches_slider), 
      slider_potential=rtg_convert(pitching_ratings_pitches_talent_slider), 
      curveball=ifelse(pitching_ratings_pitches_curveball>0, 1, 0), 
      curveball_rating=rtg_convert(pitching_ratings_pitches_curveball), 
      curveball_potential=rtg_convert(pitching_ratings_pitches_talent_curveball), 
      knucklecurve=ifelse(pitching_ratings_pitches_knucklecurve>0, 1, 0), 
      knucklecurve_rating=rtg_convert(pitching_ratings_pitches_knucklecurve), 
      knucklecurve_potential=rtg_convert(pitching_ratings_pitches_talent_knucklecurve), 
      screwball=ifelse(pitching_ratings_pitches_screwball>0, 1, 0), 
      screwball_rating=rtg_convert(pitching_ratings_pitches_screwball), 
      screwball_potential=rtg_convert(pitching_ratings_pitches_talent_screwball), 
      forkball=ifelse(pitching_ratings_pitches_forkball>0, 1, 0), 
      forkball_rating=rtg_convert(pitching_ratings_pitches_forkball), 
      forkball_potential=rtg_convert(pitching_ratings_pitches_talent_forkball), 
      fastball_all_cnt=(fastball + splitter + sinker + cutter), 
      fastball_all_avg=round((fastball_rating + splitter_rating + sinker_rating + cutter_rating)/fastball_all_cnt, 0), 
      fastball_all_pot=round((fastball_potential + splitter_potential + sinker_potential + cutter_potential)/fastball_all_cnt, 0),
      fastball_all_avg=ifelse(fastball_all_cnt==0, 0, fastball_all_avg),
      fastball_all_pot=ifelse(fastball_all_cnt==0, 0, fastball_all_pot),
      fastball_all_max_rating=pmax(fastball_rating, splitter_rating, sinker_rating, cutter_rating),
      fastball_all_max_potential=pmax(fastball_potential, splitter_potential, sinker_potential, cutter_potential),
      offspeed_all_cnt=(changeup + circlechange + knuckleball), 
      offspeed_all_avg=round((changeup_rating + circlechange_rating + knuckleball_rating)/offspeed_all_cnt, 0), 
      offspeed_all_pot=round((changeup_potential + circlechange_potential + knuckleball_potential)/offspeed_all_cnt, 0),
      offspeed_all_avg=ifelse(offspeed_all_cnt==0, 0, offspeed_all_avg),
      offspeed_all_pot=ifelse(offspeed_all_cnt==0, 0, offspeed_all_pot),
      offspeed_all_max_rating=pmax(changeup_rating, circlechange_rating, knuckleball_rating),
      offspeed_all_max_potential=pmax(changeup_potential, circlechange_potential, knuckleball_potential),
      breaking_all_cnt=(slider + curveball + knucklecurve + screwball + forkball), 
      breaking_all_avg=round((slider_rating + curveball_rating + knucklecurve_rating + screwball_rating + forkball_rating)/breaking_all_cnt, 0),
      breaking_all_pot=round((slider_potential + curveball_potential + knucklecurve_potential + screwball_potential + forkball_potential)/breaking_all_cnt, 0),
      breaking_all_avg=ifelse(breaking_all_cnt==0, 0, breaking_all_avg),
      breaking_all_pot=ifelse(breaking_all_cnt==0, 0, breaking_all_pot),
      breaking_all_max_rating=pmax(slider_rating, curveball_rating, knucklecurve_rating, screwball_rating, forkball_rating),
      breaking_all_max_potential=pmax(slider_potential, curveball_potential, knucklecurve_potential, screwball_potential, forkball_potential), 
      pitch_cnt=fastball_all_cnt+offspeed_all_cnt+breaking_all_cnt, 
      pitch_avg=round((fastball_rating + splitter_rating + sinker_rating + cutter_rating + changeup_rating + circlechange_rating + knuckleball_rating + slider_rating + curveball_rating + knucklecurve_rating + screwball_rating + forkball_rating)/pitch_cnt, 0),
      pitch_pot=round((fastball_potential + splitter_potential + sinker_potential + cutter_potential + changeup_potential + circlechange_potential + knuckleball_potential + slider_potential + curveball_potential + knucklecurve_potential + screwball_potential + forkball_potential)/pitch_cnt, 0),
      injury_prone_ovr, 
      injury_prone_arm, 
      injury_prone_leg, 
      injury_prone_back,
      personality_greed, 
      personality_loyalty, 
      personality_play_for_winner, 
      personality_work_ethic, 
      personality_intelligence, 
      personality_leader,
      season_year,
      file_name, 
      file_date)
  
};
player_status=function(){
  
  players() %>% 
    select(playerID, 
           playerNAME, 
           posID, 
           leagueID, 
           levelID, 
           orgID, 
           teamID, 
           baseballAGE, 
           season_year, 
           file_name, 
           file_date) %>% 
    left_join(ootpCSV("players_roster_status.csv") %>% 
                transmute(playerID=player_id, 
                          uniform_number, 
                          is_active, 
                          is_on_secondary, 
                          is_on_dl, 
                          is_on_dl60, 
                          is_on_waivers,
                          is_on_irrevocable_waivers=irrevocable_waivers,
                          is_on_dfa=designated_for_assignment, 
                          days_on_waivers, 
                          days_on_waivers_left, 
                          days_on_dfa_left, 
                          claimed_team_id, 
                          options_used, 
                          options_used_this_year, 
                          has_received_arbitration, 
                          trade_status, 
                          must_be_active, 
                          mlb_service_days_ytd=mlb_service_days_this_year,
                          mlb_service_years, 
                          mlb_service_days,
                          pro_service_days_ytd=pro_service_days_this_year,
                          pro_service_years, 
                          pro_service_days, 
                          dl_days_this_year, 
                          years_protected_from_rule_5, 
                          file_name, 
                          file_date), 
              by=c("playerID", "file_name", "file_date")) %>% 
    left_join(ootpCSV("players_contract.csv") %>% 
                transmute(playerID=player_id, 
                          mlb_contract=is_major, 
                          years,
                          salary_y1=salary0,
                          salary_y2=salary1,
                          salary_y3=salary2,
                          salary_y4=salary3,
                          salary_y5=salary4,
                          salary_y6=salary5,
                          salary_y7=salary6,
                          salary_y8=salary7,
                          salary_y9=salary8,
                          salary_y10=salary9,
                          ntc=no_trade,
                          last_year_team_option, 
                          last_year_player_option, 
                          last_year_vesting_option, 
                          last_year_option_buyout,
                          next_last_year_team_option, 
                          next_last_year_player_option, 
                          next_last_year_vesting_option,
                          next_last_year_option_buyout,
                          opt_out, 
                          opt_out_relegation,
                          retained,
                          minimum_pa, 
                          minimum_pa_bonus, 
                          minimum_ip, 
                          minimum_ip_bonus, 
                          mvp_bonus, 
                          cyyoung_bonus, 
                          allstar_bonus, 
                          file_name, 
                          file_date), 
              by=c("playerID", "file_name", "file_date")) %>%
    transmute(playerID, 
              playerNAME, 
              posID, 
              leagueID, 
              levelID, 
              orgID, 
              teamID, 
              baseballAGE, 
              uniform_number, 
              mlb_contract, 
              years, 
              salary_y1, 
              salary_y2, 
              salary_y3, 
              salary_y4, 
              salary_y5, 
              salary_y6, 
              salary_y7, 
              salary_y8, 
              salary_y9, 
              salary_y10, 
              ntc, 
              last_year_team_option, 
              last_year_player_option, 
              last_year_vesting_option, 
              last_year_option_buyout,
              next_last_year_team_option, 
              next_last_year_player_option, 
              next_last_year_vesting_option,
              next_last_year_option_buyout,
              opt_out, 
              opt_out_relegation,
              retained,
              minimum_pa, 
              minimum_pa_bonus, 
              minimum_ip, 
              minimum_ip_bonus, 
              mvp_bonus, 
              cyyoung_bonus, 
              allstar_bonus,
              is_active, 
              is_on_secondary, 
              is_on_dl, 
              is_on_dl60, 
              is_on_waivers, 
              is_on_irrevocable_waivers, 
              is_on_dfa, 
              days_on_waivers, 
              days_on_waivers_left, 
              days_on_dfa_left, 
              claimed_team_id, 
              options_used, 
              options_used_this_year, 
              has_received_arbitration, 
              trade_status, 
              must_be_active, 
              mlb_service_days_ytd, 
              mlb_service_years, 
              mlb_service_days, 
              pro_service_days_ytd, 
              pro_service_years, 
              pro_service_days, 
              dl_days_this_year, 
              years_protected_from_rule_5,
              season_year, 
              file_name, 
              file_date)
  
};
coaches=function(){
  
  rtg_convert=function(x){
    
    ifelse(x>=192, 
           80, 
           ifelse(x>=175, 
                  75, 
                  ifelse(x>=159, 
                         70, 
                         ifelse(x>=142, 
                                65, 
                                ifelse(x>=125, 
                                       60, 
                                       ifelse(x>=109, 
                                              55, 
                                              ifelse(x>=92, 
                                                     50, 
                                                     ifelse(x>=75, 
                                                            45, 
                                                            ifelse(x>=59, 
                                                                   40, 
                                                                   ifelse(x>=42, 
                                                                          35, 
                                                                          ifelse(x>=25, 
                                                                                 30, 
                                                                                 ifelse(x>=9, 
                                                                                        25, 
                                                                                        ifelse(x>=1, 
                                                                                               20, 
                                                                                               0)
                                                                                 )
                                                                          )
                                                                   )
                                                            )
                                                     )
                                              )
                                       )
                                )
                         )
                  )
           )
    )
    
  };
  
  ootpCSV("coaches.csv") %>% 
    left_join(nations() %>% 
                transmute(nation_id=nationID, nationDESC), 
              by="nation_id") %>%
    left_join(cities() %>% 
                transmute(city_of_birth_id=cityID, 
                          birthcityDESC=ifelse(nationID==206, 
                                               paste0(cityNAME, ", ", stateDESC), 
                                               paste0(cityNAME, ", ", nationDESC))), 
              by="city_of_birth_id") %>%
    left_join(teams() %>% 
                transmute(teamID, 
                          teamDESC, 
                          leagueID, 
                          leagueDESC,
                          levelID, 
                          levelDESC, 
                          orgID, 
                          orgDESC, 
                          season_year=leagues() %>% filter(leagueID==100) %>% pull(season_year), 
                          file_name, 
                          file_date), 
              by=c("team_id"="teamID", "file_name", "file_date")) %>%
    transmute(coachID=coach_id, 
              coachNAME=paste(first_name, last_name), 
              posID=position, 
              occID=occupation, 
              teamID=team_id,
              teamDESC=ifelse(teamID==0, "FA", teamDESC), 
              orgID=ifelse(teamID==0, 0, orgID), 
              orgDESC=ifelse(teamID==0, "FA", orgDESC),
              leagueID=ifelse(teamID==0, 0, leagueID), 
              leagueDESC=ifelse(teamID==0, "FA", leagueDESC), 
              levelID=ifelse(teamID==0, 0, levelID), 
              levelDESC=ifelse(teamID==0, "FA", levelDESC), 
              playerID=former_player_id,
              date_of_birth=lubridate::ymd(date_of_birth),
              baseballAGE=floor(as.numeric(difftime(
                lubridate::ymd(paste0(ifelse(is.na(season_year), 
                                             leagues() %>% 
                                               filter(leagueID==100) %>% 
                                               pull(season_year),
                                             season_year), 
                                      "06-30")),
                date_of_birth))/365.25), 
              birthcityID=city_of_birth_id, 
              birthcityDESC,
              nationID=nation_id,
              nationDESC,
              years_exp=experience,
              personality, 
              positive_relation, 
              negative_relation, 
              contract_years, 
              contract_salary, 
              contract_extension_years, 
              contract_extension_salary, 
              rating_manager=rtg_convert(manager_value),
              rating_base_coach=rtg_convert(basecoach_value),
              rating_pitching_coach=rtg_convert(pitching_coach_value),
              rating_hitting_coach=rtg_convert(hitting_coach_value),
              rating_scout=rtg_convert(scout_value),
              rating_doctor=rtg_convert(doctor_value),
              scout_amateur_preference, 
              scout_major=rtg_convert(scout_major),
              scout_minor=rtg_convert(scout_minor),
              scout_amateur=rtg_convert(scout_amateur),
              scout_international=rtg_convert(scout_international),
              hitting_focus, 
              pitching_focus, 
              training_focus, 
              teach_hitting=rtg_convert(teach_hitting),
              teach_pitching=rtg_convert(teach_pitching),
              teach_catcher=rtg_convert(teach_c),
              teach_infield=rtg_convert(teach_if),
              teach_outfield=rtg_convert(teach_of),
              teach_running=rtg_convert(teach_running),
              teach_ovr=rtg_convert(handle_players), 
              teach_veterans=rtg_convert(handle_veterans), 
              teach_prospects=rtg_convert(handle_rookies),
              management_style,
              lr_matchup,
              stealing, 
              running, 
              pinchrun, 
              pinchhit_pos, 
              pinchhit_pitch, 
              bunt_hit, 
              bunt, 
              hit_run, 
              run_hit, 
              squeeze, 
              hook_start, 
              hook_relief, 
              quick_left, 
              closer, 
              opener, 
              pitch_around, 
              intentional_walk, 
              hold_runner, 
              guard_lines, 
              infield_in, 
              outfield_in, 
              corners_in, 
              shift_if, 
              shift_of, 
              num_pitchers, 
              num_hitters,
              favor_speed_to_power, 
              favor_avg_to_obp, 
              favor_defense_to_offense, 
              favor_pitching_to_hitting, 
              favor_veterans_to_prospects, 
              trade_aggressiveness, 
              player_loyalty, 
              trade_frequency, 
              trade_preference, 
              value_stats, 
              value_this_year, 
              value_last_year, 
              value_two_years, 
              draft_value, 
              intl_fa_value, 
              develop_value, 
              ratings_value, 
              heal_legs=rtg_convert(heal_legs), 
              heal_arms=rtg_convert(heal_arms), 
              heal_back=rtg_convert(heal_back), 
              heal_other=rtg_convert(heal_other), 
              heal_rest=rtg_convert(heal_rest),
              prevent_legs=rtg_convert(prevent_legs),
              prevent_arms=rtg_convert(prevent_arms),
              prevent_back=rtg_convert(prevent_back),
              prevent_other=rtg_convert(prevent_other),
              season_year=ifelse(is.na(season_year), 
                                 leagues() %>% 
                                   filter(leagueID==100) %>% 
                                   pull(season_year),
                                 season_year),
              file_name, 
              file_date) %>% 
    filter(teamID==0)
  
};